# Generated by Django 5.1.1 on 2024-12-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='UserRegisterForm',
        ),
    ]
