# Generated by Django 5.1.1 on 2024-12-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_userregister_userregisterform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegisterForm',
            new_name='UserRegister',
        ),
    ]
