# Generated by Django 5.1.1 on 2024-12-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_userregister_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='User',
            new_name='user',
        ),
    ]
