# Generated by Django 5.1.1 on 2024-12-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_user_userregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='user',
        ),
        migrations.AddField(
            model_name='userregister',
            name='email',
            field=models.EmailField(default='defalut@example.com', max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(default='12345678', max_length=128),
        ),
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(default=' ', max_length=50, unique=True),
        ),
    ]
