# Generated by Django 5.1.1 on 2024-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_customuser_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'User Register',
                'verbose_name_plural': 'User Register',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
