# Generated by Django 5.1.1 on 2025-01-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_userregister_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField()),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to='reviews.userregister')),
            ],
        ),
    ]
