# Generated by Django 5.1.1 on 2025-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
