# Generated by Django 5.1.1 on 2025-02-06 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_userregister_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
