# Generated by Django 5.1.1 on 2025-02-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_remove_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
