# Generated by Django 5.1.1 on 2025-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_product_alter_review_user_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='over_view',
            field=models.TextField(db_index=True),
        ),
    ]
