# Generated by Django 5.1.1 on 2025-03-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={'verbose_name': 'Custom User ', 'verbose_name_plural': 'Custom Users '},
        ),
    ]
