# Generated by Django 5.1.1 on 2025-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('audio', 'Audio Devices'), ('wearables', 'Wearables'), ('accessories', 'Accessories')], default='smartphones', max_length=50),
            preserve_default=False,
        ),
    ]
